[package]
name = "todo"
version = "0.1.0"
authors = ["ChristianKusabs <kusabsdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
termion = "1.5.6"
dirs = "3.0.1"
